### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Nylium21** [Luwx/LightlyShaders#14]
When I try to install it on Manjaro, it gives me this error when pasting the code into the Konsole.
sudo: apt: command not found

**Comment by nonetrix** [comment]
Apt is the package manager on Ubuntu, not Arch/Manjaro on Arch you would use, ```pacman -S xyz``` but the names for the needed programs might be different

I was able to just build it without installing anything though

**Comment by Nylium21** [comment]
That would be useful, am new to Manjaro and am not used to any terms, please help me.

**Comment by Luwx** [comment]
You can install the package `lightlyshaders-git` from AUR.
