### ISSUE TITLE
How can I set shadow corner radius? 

### ISSUE THREAD

**Issue by nonetrix** [Luwx/LightlyShaders#15]
I've searched in the KDE settings, the closest thing I could find is this
![shadow](https://user-images.githubusercontent.com/45698918/127600293-817094c2-e23b-46f7-9b05-9cb6b32bf147.png)
But this doesn't give me any option to set a radius, I've tried Googling this as well with no luck, It would be nice if the read me showed where to look for this if possible

**Comment by ryu-ketsueki** [comment]
Default Breeze decoration does not have that feature. ClassikStyles improved over Breeze and added that feature
