### ISSUE TITLE
How do you get these windows without window decorations

### ISSUE THREAD

**Issue by qawsedrftgzh** [Luwx/LightlyShaders#16]
no border disables the effect completly, is this also working with gtk.

**Comment by qawsedrftgzh** [comment]
I find only "No titlebar and frame" but this hides also ther round corners

**Comment by siggsy** [comment]
Navigate to window decorations and select the pen icon in bottom right corner

![image](https://user-images.githubusercontent.com/42301860/129312226-7d72c030-36c8-4f07-b8c3-a88b0014b03f.png)


Got to "Window-Specific Overrides" tab and click "Add"

![image](https://user-images.githubusercontent.com/42301860/129312289-4406d09d-c3ca-4af1-8a6d-5d5cb7c01068.png)

Click "Detect Window Properties" or manually enter window class name of the app you want to configure or .* for all and check "Hide window title bar"
![image](https://user-images.githubusercontent.com/42301860/129312343-602660f9-bd32-4463-a4df-3f1bf550a06f.png)

As far as I have seen, You can do this on breeze and lightly window decorations

**Comment by siggsy** [comment]
If you want to keep the titlebar you can also use a script to change the titlebar color for specific apps to match the entire app: https://github.com/siggsy/Tkp

![image](https://user-images.githubusercontent.com/42301860/129312831-1471cb8f-7a60-4dae-892f-7cca20d96e5d.png)

**Comment by qawsedrftgzh** [comment]
facepalm, I looked for it in Window management -> Window rules. Thanks for your help and this link, I also searched for this.
