### ISSUE TITLE
Suggestion: remove sliders in favor of input fields

### ISSUE THREAD

**Issue by n4n0GH** [Luwx/LightlyShaders#4]
Currently the only way to set the radius of corners is done through a slider which is not reporting back the value it's going to set.

IMHO it would be better to replace the slider with a generic input field allowing for pixel value digit inputs for a much better control and also to more easily cooperate with other themes that allow for such things to be declared in pixels instead of using a slider.

**Comment by ryu-ketsueki** [comment]
Wait, there is even an option to adjust that? I can't find it.

**Comment by Luwx** [comment]
Yeah, I was planning to change it to a spinbox.

**Comment by Luwx** [comment]
Done in 3dfd3cb5c8b6754f82a466c4361f8cb0a95e24b2
