### ISSUE TITLE
Sharp corner glitch with round corners beyond KWin default

### ISSUE THREAD

**Issue by ryu-ketsueki** [Luwx/LightlyShaders#7]
This is a glitch that happens whenever the round corners slider makes the corners rounder than what they are normally without the shaders. Here's an example. This happens on all corners, not just the titlebar.
![Flameshot_202107 1_125539](https://user-images.githubusercontent.com/39316730/124161440-c9670c00-da73-11eb-898f-6fad5ca5b682.png)
![image](https://user-images.githubusercontent.com/39316730/124161539-ea2f6180-da73-11eb-9324-bdc3deb3fba4.png)

**Comment by Luwx** [comment]
The shader cannot crop the decoration shadow, this includes the outline. You'll have to compile or configure the decoration such that it has the same corner radius as the effect.

**Comment by ryu-ketsueki** [comment]
I observed the same effect with Lightly Window Decoration as well, though.

**Comment by Luwx** [comment]
Lightly decoration is capped at 8px, so if you use a larger radius in the effect the issue will happen. Maybe I should decouple the decoration and widget style corner radius.

**Comment by fauzie811** [comment]
How do yo make Konsole looks like that?

**Comment by ryu-ketsueki** [comment]
> How do yo make Konsole looks like that?

I added the options to the toolbar then added a Window Decoration rule to remove the titlebar. It's not perfect, because those aren't the real minimize and maximize buttons but at least they look cool, as if it were a true headerbar
