### ISSUE TITLE
how to uninstall this?

### ISSUE THREAD

**Issue by Aneeqasif** [Luwx/LightlyShaders#8]
i dont know how to uninstall it

**Comment by Luwx** [comment]
Open the terminal, go to the build folder (named qt5build in the install command), and type `sudo make uninstall`

**Comment by Aneeqasif** [comment]
can i decresese the roundness?

> Open the terminal, go to the build folder (named qt5build in the install command), and type `sudo make uninstall`

**Comment by Luwx** [comment]
You can configure the roundness in the effect settings, located on the "Desktop Effects" section of system settings.
