### ISSUE TITLE
Cant install on arch

### ISSUE THREAD

**Issue by yehonatan2020** [Luwx/LightlyShaders#9]
kwin_core: XCB error: 10 (BadAccess), sequence: 2064, resource id: 436, major code: 142 (Composite), minor code: 2 (RedirectSubwindows)
 ~/LightlyShaders/qt5build  qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2300, resource id: 52428812, major code: 15 (QueryTree), minor code: 0
 ~/LightlyShaders/qt5build  kwin_scripting: /home/yehudi/.local/share/kwin/scripts/sticky-window-snapping/contents/code/main.js:36: error: enabledCurrently is not defined
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2732, resource id: 52428812, major code: 20 (GetProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 6060, resource id: 37750797, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 6605, resource id: 81788940, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 9525, resource id: 23068921, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 9541, resource id: 37750798, major code: 18 (ChangeProperty), minor code: 0
kwin_core: XCB error: 152 (BadDamage), sequence: 11182, resource id: 44040850, major code: 143 (DAMAGE), minor code: 2 (Destroy)
kwin_core: XCB error: 3 (BadWindow), sequence: 11185, resource id: 67108907, major code: 129 (SHAPE), minor code: 8 (GetRectangles)

**Comment by Luwx** [comment]
The error message isn't helpful :/
